### ISSUE TITLE
Mergeo erróneo

### ISSUE THREAD

**Issue by dluqueru** [CristinaNavMor/repositorio_prueba2#4]
Has fracasado meregando las branches y ahora nos toca a nosotros solucionarlo. Ponte a ello por favor, gracias, un saludo

**Comment by CristinaNavMor** [comment]
Primero que nada, Daniel, espero que para próximas comuniaciones te comuniques conmigo de forma menos exigente y punitiva. 

Pero bueno, pasando al asunto que nos ocupa. Me encargaré de ello enseguida.

**Comment by CristinaNavMor** [comment]
Esta issue era inútil, el problema ya estaba solucionado.
