### ISSUE TITLE
Modificar stylesheet

### ISSUE THREAD

**Issue by CristinaNavMor** [CristinaNavMor/repositorio_prueba2#6]
Buenas tardes, Daniel. Acabo de volver de las vacaciones, y no me ha dado tiempo a acabar mi trabajo. ¿Podrías añadirle un borde a las tablas, por favor? 

Gracias

**Comment by dluqueru** [comment]
Buenas tardes ,Cristina. A pesar de que tu trabajo es precisamente que te de tiempo de hacer tu trabajo, he procedido a añadirle borde a las tablas. 

De nada, un saludo
